Repository microsoft/mu_feature_mm_supv, pull requests merged in 2022-08, with the labels that each got.

#15 Aligning version strings for core module and package
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: documentation

#23 Fixed missing length check in ConvertSmiHandlerSwContext()
  MmSupervisorPkg/Core/Handler/SmiHandlerProfile.c
Labels: bug, impact: security

#24 Fixed GUID comparison that could lead to arbitrary write from FreePool()
  MmSupervisorPkg/Core/Hand/Handle.c
  MmSupervisorPkg/Core/Handler/SmiHandlerProfile.c
Labels: bug, impact: security

#22 Fixed SMM_UNREG_HNDL can unregister any handler, including supervisor ones
  MmSupervisorPkg/Core/Handler/Mmi.c
  MmSupervisorPkg/Core/MmSupervisorCore.c
  MmSupervisorPkg/Core/MmSupervisorCore.h
  MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
Labels: bug, impact: security

#21 Fixed unvalidated CpuIndex (Arg2) in SMM_START_AP_PROC can cause out of bound writes
  MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
Labels: bug, impact: security

#20 Syscall entry/exit register save / restore (general purpose and FPU/MMX/SSE/AVX)
  MmSupervisorPkg/Core/PrivilegeMgmt/SysCallEntry.nasm
Labels: bug, impact: security

#19 MmFreePages() doesn't properly check NumberOfPages
  MmSupervisorPkg/Core/Mem/Page.c
  MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
Labels: bug, impact: security

#18 Fixed global length field updated even allocation in MmInstallConfigurationTable() failed
  MmSupervisorPkg/Core/Misc/InstallConfigurationTable.c
Labels: bug, impact: security

#17 Fix integer overflow in IsIoReadWriteAllowed()
  MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c
  MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.inf
  MmSupervisorPkg/Library/SmmPolicyGateLib/UnitTest/SmmPolicyGateLibUnitTest.c
  MmSupervisorPkg/Library/SmmPolicyGateLib/UnitTest/SmmPolicyGateLibUnitTest.inf
  MmSupervisorPkg/MmSupervisorPkg.ci.yaml
  MmSupervisorPkg/Test/MmSupervisorPkgHostTest.dsc
Labels: bug, impact: security

#2 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#25 Updated the version number since we moved to console build to support NX
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: documentation

#26 Fixing an edge case of incoming parameter check
  MmSupervisorPkg/Core/Mem/Page.c
Labels: bug
