Repository microsoft/mu_feature_mm_supv, pull requests merged in 2023-07, with the labels that each got.

#151 Evaluate protected regions with proper memory attribute checks
  MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvMemPolicyUnitTest.c
Labels: impact:security, impact:testing, impact:non-functional

#153 MmSupervisorPkg: Remove bare excepts
  MmSupervisorPkg/SupervisorPolicyTools/policy_entry.py
  MmSupervisorPkg/Test/MmPagingAuditTest/Windows/MemoryRangeObjects.py
Labels: impact:non-functional, language:python

#152 MmSupervisorPkg: DumpInfo to more then stdout
  MmSupervisorPkg/SupervisorPolicyTools/SupervisorPolicyMaker.py
  MmSupervisorPkg/SupervisorPolicyTools/policy_entry.py
Labels: impact:non-functional, language:python

#154 Update overrides for recent Mu Basecore CodeQL fixes
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmDxeSupport.inf
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
  MmSupervisorPkg/Drivers/StandaloneMmIpl/PiSmmIpl.c
  MmSupervisorPkg/Drivers/StandaloneMmIpl/PiSmmIpl.inf
Labels: impact:non-functional, semver:patch

#157 MmSupervisorPkg.dec: Use 16 pages for user mode comm buffer by default
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: semver:patch
