Repository microsoft/mu_feature_mm_supv, pull requests merged in 2024-04, with the labels that each got.

#263 Update Macro definition name as the patch name changes.
  SpamPkg/Include/SpamResponder.h
  SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
  SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
Labels: impact:non-functional

#267 aux_gen: Update key symbol signature format
  SpamPkg/Tools/gen_aux/readme.md
  SpamPkg/Tools/gen_aux/src/auxgen.rs
  SpamPkg/Tools/gen_aux/src/main.rs
Labels: impact:non-functional

#265 BaseLib override update
  MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
  MmSupervisorPkg/Library/BaseLibSysCall/CheckSum.c
Labels: impact:breaking-change

#255 SpamBinBuild: Patch aux file hash into Stm.bin
  SpamPkg/Core/Stm.inf
  SpamPkg/SpamBinBuild.py
  SpamPkg/SpamPkg.dec
  SpamPkg/Tools/GenSpamArtifacts/GenAux.bat
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts_plug_in.json
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/.gitignore
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/Cargo.toml
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/readme.md
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/src/auxgen.rs
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/src/main.rs
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/src/util.rs
  SpamPkg/Tools/GenSpamArtifacts/gen_aux/src/validation.rs
  SpamPkg/Tools/GenSpamArtifacts/tool_path_env.yaml
Labels: impact:non-functional, language:python

#270 GenSpamArtifacts.py: Support Python 3.10, 3.11
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Labels: impact:non-functional, language:python

#271 GenSpamArtifacts.py: Add MmiEntrySpam.bin and debug files
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Labels: impact:non-functional, language:python

#273 Removing cfg file from MmSupervisor package
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Core/aux_config.spam.cfg
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Labels: language:python

#279 Integrate image record changes from MU_BASECORE
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
  MmSupervisorPkg/Core/Misc/MemoryAttributesTable.c
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
  MmSupervisorPkg/MmSupervisorPkg.dsc
Labels: impact:breaking-change

#280 Update release version to v11 to match release versioning
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: impact:non-functional

#278 Integrate validation routine into SPAM core
  .pytool/CISettings.py
  SpamPkg/Core/CpuDef.h
  SpamPkg/Core/Runtime/SmiHandler.c
  SpamPkg/Core/Runtime/SmmEptHandler.c
  SpamPkg/Core/Runtime/SpamResponderReport.c
  SpamPkg/Core/Runtime/SpamResponderUtilities.c
  SpamPkg/Core/Runtime/StmRuntime.h
  SpamPkg/Core/Stm.h
  SpamPkg/Core/Stm.inf
  SpamPkg/Include/Library/PeCoffLibNegative.h
  SpamPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SpamPkg/Library/HashLibTpm2Raw/HashLibTpm2Raw.c
  SpamPkg/SpamPkg.dsc
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Labels: language:python

#284 Fix Dsc offsets in MmiEntrySpam.nasmb
  SpamPkg/Core/Runtime/SmmEptHandler.c
  SpamPkg/Core/Runtime/SpamResponderUtilities.c
  SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
  SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
Labels: impact:non-functional

#287 Expand common secure policy library to accept page table address as input
  MmSupervisorPkg/Core/Request/FetchPolicy.c
  MmSupervisorPkg/Include/Library/SecurePolicyLib.h
  MmSupervisorPkg/Library/SecurePolicyLib/MemPolicy.c
  SpamPkg/Core/Runtime/SpamResponderReport.c
Labels: impact:breaking-change

#289 Added MmSupervisorCoreGuid
  MmSupervisorPkg/Core/MmSupervisorCore.c
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/MmSupervisorPkg.ci.yaml
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: impact:non-functional

#290 Port Recent MpService Changes [Rebase & FF]
  MmSupervisorPkg/Core/Services/MpService/MpService.c
Labels: semver:patch

#285 Add a test for validation routine to be used in supervisor core
  SpamPkg/Core/Test/ResponderValidationTestLib.c
  SpamPkg/Core/Test/ResponderValidationTestLib.inf
  SpamPkg/Include/Guid/SpamTestCommRegion.h
  SpamPkg/SpamPkg.dec
  SpamPkg/SpamPkg.dsc
  SpamPkg/Tests/ResponderValidationTest/ResponderValidationTestApp.c
  SpamPkg/Tests/ResponderValidationTest/ResponderValidationTestApp.inf
  SpamPkg/Tests/ResponderValidationTest/readme.md
Labels: impact:testing, impact:non-functional
