Repository microsoft/mu_feature_mm_supv, pull requests merged in 2024-10, with the labels that each got.

#349 Update override hash on PiSmmCore
  MmSupervisorPkg/Core/Handler/Mmi.c
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Labels: impact:security, impact:breaking-change

#352 gen_aux: Allow validation rules to only apply to certain build targets
  MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:non-functional, language:python

#351 gen_rim: Update uuid encoding byteorder
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/lib.rs
Labels: impact:non-functional

#357 Update override and tracking tags for StandaloneMmHobLib
  MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
  MmSupervisorPkg/Library/MmSupervisorMemLib/MmSupervisorMemLibSyscall.inf
  MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.inf
Labels: impact:non-functional

#364 Updated OverrideValidation hashes for new basecore
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Labels: impact:non-functional
