Repository microsoft/mu_feature_mm_supv, pull requests merged in 2024-08, with the labels that each got.

#317 Changed AllocatePageTableMemory to include a new variable
  MmSupervisorPkg/Core/Mem/Mem.h
  MmSupervisorPkg/Core/Mem/PageTbl.c
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
Labels: type:bug, impact:security

#322 Document update and version change
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  MmSupervisorPkg/MmSupervisorPkg.dec
Labels: impact:non-functional

#325 Update feature/spam branch
  .azurepipelines/MuDevOpsWrapper.yml
  .gitattributes
  .github/workflows/auto-approve.yml
  .github/workflows/auto-merge.yml
  .github/workflows/codeql.yml
  .github/workflows/issue-assignment.yml
  .github/workflows/label-issues.yml
  .github/workflows/label-sync.yml
  .github/workflows/release-draft.yml
  .github/workflows/stale.yml
  .github/workflows/triage-issues.yml
  MmSupervisorPkg/Core/Dispatcher/Dispatcher.c
  MmSupervisorPkg/Core/Mem/Mem.h
  MmSupervisorPkg/Core/Mem/PageTbl.c
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
  MmSupervisorPkg/Core/Misc/MemoryAttributesTable.c
  MmSupervisorPkg/Core/MmSupervisorCore.h
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Core/Relocate/Relocate.c
  MmSupervisorPkg/Core/Relocate/Relocate.h
  MmSupervisorPkg/Core/Request/UnblockMemory.c
  MmSupervisorPkg/Core/Services/MpService/MpService.c
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
  MmSupervisorPkg/MmSupervisorPkg.dec
  MmSupervisorPkg/MmSupervisorPkg.dsc
  MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c
  SpamPkg/MmiEntrySpam/MmiEntrySpam.inf
  pip-requirements.txt
Labels: impact:non-functional

#329 SeaPkg: Add SeaManifestPublicationLib
  SeaPkg/Include/Guid/SeaManifest.h
  SeaPkg/Include/Library/SeaManifestPublicationLib.h
  SeaPkg/Library/BaseSeaManifestPublicationLibNull/BaseSeaManifestPublicationLibNull.c
  SeaPkg/Library/BaseSeaManifestPublicationLibNull/BaseSeaManifestPublicationLibNull.inf
  SeaPkg/Library/DxeSeaManifestPublicationLibConfigTable/DxeSeaManifestPublicationLibConfigTable.c
  SeaPkg/Library/DxeSeaManifestPublicationLibConfigTable/DxeSeaManifestPublicationLibConfigTable.inf
  SeaPkg/SeaPkg.dec
  SeaPkg/SeaPkg.dsc
Labels: impact:non-functional, type:feature-request

#330 StmInit: Validate SeaVmcallDispatcher() parameter
  SeaPkg/Core/Init/StmInit.c
Labels: impact:non-functional

#332 gen_rim: add signature structure generation capability
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/lib.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/main.rs
Labels: impact:non-functional, language:python

#333 Read signature from bin
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/main.rs
Labels: impact:non-functional
