Repository microsoft/mu_feature_mm_supv, pull requests merged in 2024-06, with the labels that each got.

#300 Fixing override validation failure
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Core/Relocate/Relocate.c
Labels: impact:non-functional

#297 Update the core to compare hash with patched digest value during build
  MmSupervisorPkg/Library/SecurePolicyLib/MemPolicy.c
  SpamPkg/Core/Runtime/SmiHandler.c
  SpamPkg/Core/Runtime/SpamResponderReport.c
  SpamPkg/Core/Runtime/StmRuntimeUtil.h
  SpamPkg/Core/Stm.inf
  SpamPkg/Core/Test/ResponderValidationTestLib.c
  SpamPkg/Core/Test/ResponderValidationTestLib.inf
  SpamPkg/Include/Guid/SpamTestCommRegion.h
  SpamPkg/Include/SpamResponder.h
  SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
  SpamPkg/Library/SmmCpuFeaturesLib/StandaloneMmCpuFeaturesLibStm.inf
  SpamPkg/SpamPkg.dec
  SpamPkg/Tests/ResponderValidationTest/ResponderValidationTestApp.c
  SpamPkg/Tests/ResponderValidationTest/ResponderValidationTestApp.inf
  SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Labels: impact:security, impact:breaking-change, impact:testing, language:python

#302 Fix uninitialized variables for CLANG
  MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c
Labels: type:bug

#304 Fixing override break due to PiSmmCpuDxeSmm updates
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Core/Relocate/Relocate.c
Labels: impact:breaking-change

#307 Fixing override break due to PiSmmCpuDxeSmm updates.
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: impact:non-functional
