Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-02, with the labels that each got.

#395 Add ability to generate a dummy config file with all parsed symbols
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:non-functional

#396 Make it so PiSmmCpuSmiEntryFixupAddress is only called when not using SEA
  MmSupervisorPkg/Core/Relocate/Relocate.c
Labels: impact:non-functional

#397 Switch target filtering to scopes
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:breaking-change, impact:non-functional, type:design-change, language:python

#390 MmSupervisorPkg: Add MmSupervisorRing3Performance
  MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  MmSupervisorPkg/Docs/PlatformIntegration/SoftwareComponentOverview.md
  MmSupervisorPkg/Drivers/MmSupervisorRing3Performance/MmSupervisorRing3Performance.c
  MmSupervisorPkg/Drivers/MmSupervisorRing3Performance/MmSupervisorRing3Performance.inf
  MmSupervisorPkg/MmSupervisorPkg.dsc
Labels: type:documentation, type:feature-request

#402 MmSupervisorPkg/Ring3Broker: Add StandaloneMmCore track tag
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Labels: impact:non-functional

#405 MmSupervisorPkg/SmmCpuMemoryManagement: Print invalid address points
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
Labels: impact:non-functional

#404 SeaPkg: Make Image Validation Testable
  SeaPkg/Core/Runtime/SeaResponderReport.c
  SeaPkg/Include/Library/PeCoffLibNegative.h
  SeaPkg/Include/Library/PeCoffValidationLib.h
  SeaPkg/Include/SeaAuxiliary.h
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.inf
  SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
  SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.inf
  SeaPkg/SeaPkg.dec
  SeaPkg/SeaPkg.dsc
Labels: impact:breaking-change, impact:non-functional

#381 Move the GDT data to be read only data section
  MmSupervisorPkg/Core/Relocate/SmiException.nasm
Labels: impact:security
