Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-06, with the labels that each got.

#488 Move core private data to local variable and
  MmSupervisorPkg/Core/MmSupervisorCore.c
  MmSupervisorPkg/Core/MmSupervisorCore.h
  MmSupervisorPkg/Core/Policy/GeneralPolicy.c
Labels: type:bug

#491 MmSupervisorPkg: Update SysCall BaseLib hashes.
  MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
Labels: impact:non-functional

#490 MmSupervisorPkg: Add missing MmCoreDataHobGuid.
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: type:bug, impact:non-functional

#493 test-aux: Add scope parameter for aux generation
  SeaPkg/Tools/GenSeaArtifacts/test_aux/src/main.rs
Labels: type:bug, impact:non-functional

#474 aux_gen: Add new `guid` rule to `[[rule]]`
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/config.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs
Labels: impact:non-functional

#495 aux_gen: Add remarks config to [[rule]]
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/config.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
  SeaPkg/Tools/GenSeaArtifacts/test_aux/src/main.rs
Labels: impact:non-functional

#500 Remove PCI related content from this repository
  MmSupervisorPkg/MmSupervisorPkg.dsc
  SeaPkg/Core/Init/Paging.c
  SeaPkg/Core/Stm.h
  SeaPkg/Core/Stm.inf
  SeaPkg/SeaPkg.dsc
Labels: impact:non-functional
