Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-05, with the labels that each got.

#471 Add SEA CPU information library
  MmSupervisorPkg/Core/PrivilegeMgmt/SysCallEntry.nasm
  SeaPkg/Include/Library/SeaCpuInformationLib.h
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.inf
  SeaPkg/Library/BaseSeaCpuInformationLibNull/BaseSeaCpuInformationLibNull.c
  SeaPkg/Library/BaseSeaCpuInformationLibNull/BaseSeaCpuInformationLibNull.inf
  SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
  SeaPkg/SeaPkg.ci.yaml
  SeaPkg/SeaPkg.dec
  SeaPkg/SeaPkg.dsc
Labels: impact:breaking-change

#432 Update for 202502
  .pytool/CISettings.py
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmDxeSupport.inf
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.c
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplX64Relay.inf
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
  MmSupervisorPkg/Include/Guid/MmCoreData.h
  MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
  MmSupervisorPkg/Library/MmSupervisorMemLib/MmSupervisorCoreMemLib.inf
  MmSupervisorPkg/Library/MmSupervisorUnblockMemoryLib/MmSupervisorUnblockMemoryLibPei.inf
  MmSupervisorPkg/Library/StandaloneMmDriverEntryPoint/StandaloneMmDriverEntryPoint.inf
  MmSupervisorPkg/MmSupervisorPkg.dec
  MmSupervisorPkg/MmSupervisorPkg.dsc
  MmSupervisorPkg/Test/MmiHandlerProfileInfo/MmiHandlerProfileInfo.inf
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.inf
  SeaPkg/MmiEntrySea/MmiEntrySea.inf
  SeaPkg/SeaPkg.dsc
Labels: impact:non-functional

#465 gen_aux: Large Clean-up for reusability
  SeaPkg/Tools/GenSeaArtifacts/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/bin/create_aux.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/bin/create_config.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/config.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/file.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/lib.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/type_info.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_manifest/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/rustfmt.toml
Labels: impact:non-functional, language:python

#475 Add an image dump when encountering a validation error
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
Labels: impact:non-functional

#483 Remove setting the .bss section as a none section
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: impact:non-functional
