Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-01, with the labels that each got.

#379 Remove SMM profile code
  MmSupervisorPkg/Core/Mem/PageTbl.c
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
  MmSupervisorPkg/Core/Mem/SmmProfile.c
  MmSupervisorPkg/Core/Mem/SmmProfile.h
  MmSupervisorPkg/Core/Mem/SmmProfileArch.c
  MmSupervisorPkg/Core/Mem/SmmProfileArch.h
  MmSupervisorPkg/Core/Mem/SmmProfileInternal.h
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Core/Relocate/Relocate.c
  MmSupervisorPkg/Core/Relocate/Relocate.h
  MmSupervisorPkg/Core/Relocate/SmiException.nasm
  MmSupervisorPkg/Core/Services/MpService/MpService.c
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.c
  MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
Labels: impact:security

#384 Resolve override validation failure due to hob lib changes
  .pytool/CISettings.py
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
  MmSupervisorPkg/Library/MmSupervisorMemLib/MmSupervisorMemLibSyscall.inf
  MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.c
  MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.inf
Labels: impact:non-functional

#385 Remove `PeCoffLibNegative` from supervisor inf
  MmSupervisorPkg/Core/MmSupervisorCore.inf
  MmSupervisorPkg/MmSupervisorPkg.dsc
Labels: type:bug, impact:non-functional

#386 Separate .bss section from the .data sections in the RELEASE image
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: impact:non-functional

#388 Change override tag to tracking tag
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: impact:non-functional
