Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-04, with the labels that each got.

#428 Fixed issues with the pointer validation code
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
  SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
Labels: impact:testing, impact:non-functional

#451 gen_aux: Move array configuration to an 'array' parent
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:breaking-change, impact:non-functional

#452 Remove/Modify some global variables
  MmSupervisorPkg/Core/FwVol/FwVol.c
  MmSupervisorPkg/Core/Mem/HeapGuard.c
  MmSupervisorPkg/Core/Mem/PageTbl.c
  MmSupervisorPkg/Core/Mem/SmmProfile.c
  MmSupervisorPkg/Core/Mem/SmmProfile.h
  MmSupervisorPkg/Core/Relocate/Relocate.c
  MmSupervisorPkg/Core/Relocate/Relocate.h
  MmSupervisorPkg/Core/Test/PagingAudit.c
Labels: impact:non-functional

#453 gen_aux: Provide default value for sentinel
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:non-functional

#454 gen_aux: Ignore symbols outside of read/write section
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
Labels: impact:non-functional

#455 Override VS2022 release DLINK_FLAGS for the MmSupervisorCore
  MmSupervisorPkg/Core/MmSupervisorCore.inf
Labels: impact:non-functional

#456 gen_aux: Deny unknown config file fields
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:non-functional

#407 Protect MSEG region and verify protection during validation
  SeaPkg/Include/SeaResponder.h
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLibCommon.c
  SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
Labels: impact:security

#458 aux_gen: properly calculate array length
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/type_info.rs
Labels: type:bug, impact:non-functional

#459 Fix bug around updating the StmHeader in MSEG
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
Labels: impact:non-functional

#461 Update self ref validation to use the original image for validation
  SeaPkg/Include/Library/PeCoffValidationLib.h
  SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
  SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
Labels: type:bug, impact:non-functional

#462 Change heapguard global variables to CONST
  MmSupervisorPkg/Core/Mem/HeapGuard.c
Labels: impact:non-functional

#469 Fix whacked exception handler
  MmSupervisorPkg/Core/Mem/PageTbl.c
  MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
  MmSupervisorPkg/Core/Relocate/Relocate.c
Labels: type:bug
