Repository microsoft/mu_feature_mm_supv, pull requests merged in 2025-03, with the labels that each got.

#414 GenSeaArtifacts: Remove RIM generation
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/lib.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/main.rs
Labels: impact:non-functional, language:python, semver:major

#413 Initial documentation for SEA
  SeaPkg/Docs/PlatformIntegration/Images/asset_layout.png
  SeaPkg/Docs/PlatformIntegration/Images/validation_illustration.png
  SeaPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SeaPkg/Docs/PlatformIntegration/SoftwareComponentOverview.md
Labels: type:documentation, impact:non-functional

#417 auxgen: Ignore labels for required symbols config
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
Labels: type:enhancement, type:design-change, semver:minor

#411 gen_aux: Add rule coverage report
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Labels: impact:non-functional, language:python, semver:minor

#418 aux_gen: Fix bugs in tool
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
Labels: type:bug, type:enhancement

#415 GenSeaArtifacts: simplify rust integration
  SeaPkg/Tools/GenSeaArtifacts/.gitignore
  SeaPkg/Tools/GenSeaArtifacts/Cargo.toml
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Labels: impact:non-functional, language:python

#422 GenSeaArtifacts: Move aux to misc dir
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Labels: impact:breaking-change, impact:non-functional, language:python

#421 SeaPkg: include manual build documentation.
  SeaPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Labels: type:documentation, impact:non-functional, language:python

#425 gen_aux: raw data report updates
  SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
Labels: impact:non-functional

#433 rule coverage: Add helper function to validate
  SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Labels: impact:non-functional, language:python
